<html>
<head><title>CockyMoviesManager</title>
<style type="text/css">
.auto-style1 {
	text-align: center;
}
</style>
</head>
<body>
<form id="form1" runat="server">
	<div class="auto-style1">
		<br>
		<asp:Image id="Image1" runat="server" ImageUrl="./cocky547.png" />
		<br><br><br><br>STORE 33 MOVIE MANAGER - COLUMBIA, SC<br>2300 FORREST 
		DRIVE<br />
        RATINGS TYPES<br />
        <br>
		<div class="auto-style1">
			<asp:GridView id="GridView1" runat="server" AllowSorting="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True" DataKeyNames="Id" DataSourceID="SqlDataSource1" Width="1408px" horizontalalign="Center" EnableModelValidation="True" AllowPaging="True">
				<Columns>
					<asp:BoundField DataField="Id" HeaderText="Id" InsertVisible="False" ReadOnly="True" SortExpression="Id">
					</asp:BoundField>
					<asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name">
					</asp:BoundField>
				</Columns>
			</asp:GridView>
		</div>
	</div>
	<asp:SqlDataSource id="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:cm_dbConnectionString2 %>" OldValuesParameterFormatString="original_{0}" ProviderName="<%$ ConnectionStrings:cm_dbConnectionString2.ProviderName %>" SelectCommand="SELECT * FROM  ratings " ConflictDetection="CompareAllValues" DeleteCommand="DELETE FROM  ratings  WHERE  Id  = ? AND (( Name  = ?) OR ( Name  IS NULL AND ? IS NULL))" InsertCommand="INSERT INTO  ratings  ( Id ,  Name ) VALUES (?, ?)" UpdateCommand="UPDATE  ratings  SET  Name  = ? WHERE  Id  = ? AND (( Name  = ?) OR ( Name  IS NULL AND ? IS NULL))">
		<DeleteParameters>
			<asp:Parameter Name="original_Id" Type="Int32" />
			<asp:Parameter Name="original_Name" Type="String" />
			<asp:Parameter Name="original_Name" Type="String" />
		</DeleteParameters>
		<InsertParameters>
			<asp:Parameter Name="Id" Type="Int32" />
			<asp:Parameter Name="Name" Type="String" />
		</InsertParameters>
		<UpdateParameters>
			<asp:Parameter Name="Name" Type="String" />
			<asp:Parameter Name="original_Id" Type="Int32" />
			<asp:Parameter Name="original_Name" Type="String" />
			<asp:Parameter Name="original_Name" Type="String" />
		</UpdateParameters>
	</asp:SqlDataSource>

<div><a href="insertstar.aspx">Insert a New Star</a></div>

</form>

</body>
</html>